# frozen_string_literal: true

source 'https://rubygems.org'

# Ruby
gem 'coveralls'
gem 'json'
gem 'minitest'
gem 'minitest-ci'
gem 'oj'
gem 'ruby-prof'
gem 'simplecov', '0.21.2'

# Rack
gem 'prometheus-client'
gem 'puma'
gem 'rack'
gem 'rack-test'
gem 'rest-client'
gem 'thin'

# Sinatra
gem 'capybara'
gem 'extjs'
gem 'nokogiri'
gem 'sass'
gem 'sassc'
gem 'selenium-webdriver'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sprockets'
gem 'uglifier'
gem 'uri'
